Only cache valid response
rokucommunity/roku-requests pull request #31
Opened 2023-01-11 15:22 UTC by iBicha

I've hit a case where bad responses were being cached, and then I'm stuck on the bad cache over and over.
Should cache only when we have a valid response

2023-01-14 17:57 UTC, iBicha commented
cc @TwitchBronBron

2023-01-19 13:36 UTC, TwitchBronBron requested changes
Looks great! Just one small tweak and then I'm happy to merge this.

Whenever I cuta release, I auto-generate the changelog based on all the commits and then hand-edit them so they're nicer for humans. So you can just exclude the changelog edit entirely if you'd like

2023-01-19 13:36 UTC, TwitchBronBron commented on CHANGELOG.md
> +
Can you move this up to `[unreleased]` since [1.1.0](https://github.com/rokucommunity/roku-requests/releases/tag/v1.1.0) has already been published?

2023-01-19 14:39 UTC, iBicha commented
> Looks great! Just one small tweak and then I'm happy to merge this.
> 
> Whenever I cut a release, I auto-generate the changelog based on all the commits and then hand-edit them so they're nicer for humans. So you can just exclude the changelog edit entirely if you'd like

Good to know, I removed the changelog altogether!

2023-01-19 15:18 UTC, TwitchBronBron approved these changes

2023-01-19 15:19 UTC, merged